apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: httpd:2.4-alpine
        name: httpd
        volumeMounts:
        - name: volume-web
          mountPath: /usr/local/apache2/htdocs
      volumes: 
      - name: volume-web
        hostPath:
          path: /data/web