apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: producteur
spec:
  selector:
    matchLabels:
      app3: producteur
  template:
    metadata:
      labels:
        app3: producteur
    spec:
      containers:
      - name: producteur
        image: alpine:3.12
        command: ["sh","-c"]
        args:
          - while true;
            do 
              echo  "le Hostname est $(hostname) et la date est $(date)" > /web/index.html;
              sleep 60;
            done 
        volumeMounts:
        - name: volume-web
          mountPath: /web
      volumes: 
      - name: volume-web
        hostPath:
          path: /data/web