apiVersion: v1
kind: PersistentVolume 
metadata:
    name: volume-web 
spec:
    storageClassName: manual
    capacity:
      storage: 200Mi
    accessModes:
    - ReadWriteOnce
    hostPath:
      path: /data/web